apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flonest
  namespace: flonest
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 25m
spec:
  ingressClassName: nginx
  rules:
    - host: flonest.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: flonest-api
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flonest-web
                port:
                  number: 80